/*
 * auto generated by gen.py
 *
 * stub_{{group}}.h
 *
 *  Created on: Sep 5, 2015
 *      Author: meng
 */

#ifndef STUB_{{group}}_H_
#define STUB_{{group}}_H_

#include <linux/kernel.h>
#include <linux/syscalls.h>

#include "logger.h"
#include "sync.h"

/* for struct definitions */
{{syscall_includes}}

{{syscall_headers}}

#endif /* STUB_{{group}}_H_ */
